### ISSUE TITLE
Error not immediatly fired on client-side

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/ezpaarse#10]
When the format of the first line can't be recognized, the server ends the response but the client doesn't do anything, and the progress bar freezes at its current progress.

The other errors are correctly handled on client side, probably because the response is immediate in those cases. In case of unknown format, the request has to be read a bit before the error can be sent.

**Comment by nojhamster** [comment]
This problem affects ajax requests in both chrome and firefox, but cURL behaves correctly.

**Comment by nojhamster** [comment]
The server was sending the headers along with the heartbeat, that's why the status code couldn't be set in case of wrong format. Now it waits for at least one line to be parsed before it initiate the heartbeat.

**Comment by pseudom** [comment]
Bien joué !
Le 3 mars 2016 6:54 PM, "Yannick Schurter" <notifications@github.com> a
écrit :
