### ISSUE TITLE
Crossref: allow for realtime interrogation

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/ezpaarse#13]
For bibliolog-like applications

**Comment by kerphi** [comment]
Don't understand what it really means ?

**Comment by nojhamster** [comment]
The crossref middleware keeps ECs in a buffer in order to query multiple DOIs in a single request to the API, which is not compatible with the realtime use of bibliolog.

But now that I'm thinking about it, the buffer size can already be changed with a header. So maybe this isn't a real issue.

**Comment by kerphi** [comment]
Ok thanks.
So we just have to set buffer size = 1 throught the header to make it real
time compatible ? :)

**Comment by nojhamster** [comment]
It should be okay that way :)
