### ISSUE TITLE
Failed to initialize parser list

### ISSUE THREAD

**Issue by rsirres** [ezpaarse-project/ezpaarse#130]
I updated ezpaarse with the command `make update`. However, I am unable to start ezpaarse properly.

In the `log/forever.log` I see the following error message:
```
error: Script restart attempt #10
2021-11-15T15:47:50.242Z info: ezpaarse v3.7.2 | PID: 87660 | Mode: production
2021-11-15T15:47:50.544Z info: MongoDB version: 3.6.3
2021-11-15T15:47:53.369Z error: Failed to initialize parser list: Unexpected string in JSON at position 1044
error: Forever detected script exited with code: 1
```

Looks like EZpaarse is unable to parse a specific JSON file. Do you know how I can determine which parser is the culprit ?

**Comment by rsirres** [comment]
Ok the problem lies here:

https://github.com/ezpaarse-project/ezpaarse-platforms/blob/master/ovid/manifest.json#L42

**Comment by pseudom-univ** [comment]
we update the parser so ti shoud be working now

**Comment by pseudom-univ** [comment]
This commit https://github.com/ezpaarse-project/ezpaarse-platforms/commit/bcb256f9a1bb09e71b2a3ce00a9285877bae6744 should resolve the issue

**Comment by pseudom** [comment]
This commit ezpaarse-project/ezpaarse-platforms@bcb256f should resolve the issue

**Comment by pseudom** [comment]
Thanks for pointing this !

You have to update the platform directory of your ezpaarse instance now
