### ISSUE TITLE
Outdated Debian base image

### ISSUE THREAD

**Issue by kgilje** [ezpaarse-project/ezpaarse#165]
The base image of node:14.17.6 (https://github.com/ezpaarse-project/ezpaarse/blob/5ed41db3d3c94ab1ebce4774d4fb024bd6450cdd/Dockerfile#L1) relies on **debian:stretch-20210902** (https://hub.docker.com/layers/library/node/14.17.6/images/sha256-d8af604130d324909081188092c3b49e886a3a493c7b57c011a155e62e51358e?context=explore [https://hub.docker.com/layers/library/debian/stretch-20210902/images/sha256-12091b7b[…]7775c552b515d12e9196788057aad040e193f90fb2316?context=explore](https://hub.docker.com/layers/library/debian/stretch-20210902/images/sha256-12091b7bca02f4adced7775c552b515d12e9196788057aad040e193f90fb2316?context=explore)) which is **no longer being supported** according to the debian list of supported tags (https://hub.docker.com/_/debian).  Debian 9.9 packages have been archived preventing the use of updated software inside the container.  Please update your node version to get a more up-to-date (supported) debian version.

**Comment by oxypomme** [comment]
Hey

We just released the new version (3.9.0) in 9fcff1b on dockerhub.
