### ISSUE TITLE
Optimize the paquet handling in the crossref middleware

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/ezpaarse#17]
Currently, we browse the crossref results once for each EC until we find a matching DOI, which means that we loop `paquetSize / 2` times in average.

A better implementation would be to iterate once over the results to make a `DOI<->Result` map, and then iterate once over the ECs and use this map to merge the results. This would greatly decrease the number of loops.

**Comment by tporquet** [comment]
A cache mechanism has been implemented a while ago 
https://github.com/ezpaarse-project/ezpaarse-middlewares/commit/469527c071bceaf321e991e3680c48244d489b40#diff-eda6a9574cdb5b1d6f499e337f711fe0
