### ISSUE TITLE
blank field in admin when editing a user

### ISSUE THREAD

**Issue by kerphi** [ezpaarse-project/ezpaarse#18]
Example:
![image](https://cloud.githubusercontent.com/assets/328244/11504456/cb8d0938-9845-11e5-86e4-69be6d3d6ccc.png)

When I click on "Sauvegarder" I will have:
![image](https://cloud.githubusercontent.com/assets/328244/11504478/e9c6850a-9845-11e5-88a3-5ea0bf0dc1f1.png)

But that's not too bad because if I reload the web page I will have the right saved data.

**Comment by tporquet** [comment]
+1
