### ISSUE TITLE
Use the first N lines to test the log format

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/ezpaarse#24]
As of now, only the first line is used to test the log format. But sometimes, the very first line can contain anomalies for some reason, causing the job to fail. ezPAARSE should try to parse the N first lines. This number would be customizable via a header (something like `ezPAARSE-Max-Parse-Fails`) with a default value around 10-20.

**Comment by nojhamster** [comment]
Implemented with a default value of **10** and customizable via [Max-Parse-Attempts](http://ezpaarse-preprod.couperin.org/doc/parametres.html#max-parse-attempts)

**Comment by kerphi** [comment]
Great feature, thanks a lot Yannick !
