### ISSUE TITLE
lib/bin/ecbulkmaker is bypassing valid log files

### ISSUE THREAD

**Issue by a-cordier** [ezpaarse-project/ezpaarse#27]
With a source directory containing files like " ezproxy.log-20141231.gz" the regex used to detect whether the file should be processed or not does not match

**Comment by a-cordier** [comment]
In this proper situation with /^.*(\.gz|\.log)$/.test(file)  we get a match

**Comment by nojhamster** [comment]
Thanks for pointing this out, it should handle `.log`, `.log.gz` and `.gz` now :)
