### ISSUE TITLE
The mongodb prerequisite has to be made more explicit in the documentation

### ISSUE THREAD

**Issue by tporquet** [ezpaarse-project/ezpaarse#30]
I think we should mention mongodb as soon as the readme.md, instead of only in https://github.com/ezpaarse-project/ezpaarse/blob/master/doc/quickstart.md (which is 3 clicks away).

**Comment by nojhamster** [comment]
Do you think that the current [beta structure](http://ezpaarse.readthedocs.org/en/rtd-sphinx/) could do the job ? (ie. the explicit "requirements" section with mongodb in it)

**Comment by tporquet** [comment]
Yes, this is what I had in mind!
thx
