### ISSUE TITLE
Install error on a new lubuntu system

### ISSUE THREAD

**Issue by symac** [ezpaarse-project/ezpaarse#46]
Trying to install ezpaarse based on the Readme instructions, I encounter an error message : 
```
ln: impossible de créer le lien symbolique '/home/ezpaarse/test/ezpaarse/build/nvm/bin/latest': Aucun fichier ou dossier de ce type
Makefile:98 : la recette pour la cible « nodejs » a échouée
```
It can be fixed by manually running the command:
```
mkdir build/nvm/bin/
```
from the install directory but it should be done by the makefile. Sorry for just opening the issue and not submitting a patch but my Makefile skills are below the required level :)

**Comment by nojhamster** [comment]
Actually, this issue appeared some days ago and has just been resolved in d1800cb96c7cd18c837e8964360f89dd76717067. The way we load node into the environment has changed.

**Comment by kerphi** [comment]
should we generat a new ezpaarse version ?

**Comment by nojhamster** [comment]
**v2.9.1** generated

**Comment by tporquet** [comment]
Hello @symac ! Have you been able to test with this new version? Does it work like expected?

**Comment by symac** [comment]
Sorry for replying late, everything is fine now, just tried a new install on a freshly installed Ubuntu and everything is ok, thanks.
