### ISSUE TITLE
Travis build fails since node v6.6.0

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/ezpaarse#47]
Travis didn't build the commit dedicated to the migration to node 6, so it's not clear if the problem has been introduced by node 6 or by the modules update. I can't reproduce the problem on my machine, so it's seems to be specific to the Travis environment.

**Comment by kerphi** [comment]
test are ok on my local machine too

**Comment by nojhamster** [comment]
It seems that the problem isn't related to node 6, but rather to a new version of bufferutils. Investigating...

**Comment by nojhamster** [comment]
Downgrading socket.io to 1.3.7 fixes the issue.

**Comment by nojhamster** [comment]
Somehow, downgrading socket.io to 1.3.7 didn't fix the issue on the **master** branch. The reason remains mysterious...

**Comment by nojhamster** [comment]
Fixed in f76e58cebf613f206c24c3ffb6566a6f6deead2b, I'm going to update socket.io back to 1.4 and then i'll generate a version **1.9.3**

**Comment by kerphi** [comment]
this issue gave me the answer:
https://github.com/travis-ci/travis-ci/issues/4771
