### ISSUE TITLE
National instance is only for demo purposes

### ISSUE THREAD

**Issue by pseudom** [ezpaarse-project/ezpaarse#49]

**Comment by pseudom** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Préciser sur l'instance nationale que c'est un outil de démo](https://trello.com/c/Q0sCSRF6/95-preciser-sur-l-instance-nationale-que-c-est-un-outil-de-demo)

**Comment by nojhamster** [comment]
Implemented in v2.9.4
