### ISSUE TITLE
docker-compose up --> endless loop

### ISSUE THREAD

**Issue by tporquet** [ezpaarse-project/ezpaarse#54]

**Comment by tporquet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [docker-compose up --> boucle infinie](https://trello.com/c/EQn9P9Yu/133-docker-compose-up-boucle-infinie)

**Comment by nojhamster** [comment]
Normally, docker wait 2 times longer at each attempt. The interesting lines are :

```bash
ezpaarse | ezPAARSE-2.8.0 listening on http://localhost:59599 (pid is 54)  
ezpaarse | Matching list built. (2647 domains registered for 96 platforms)  
ezpaarse |  
ezpaarse | events.js:141  
ezpaarse | throw er; // Unhandled 'error' event  
ezpaarse | ^  
ezpaarse |  
ezpaarse | Error: listen EADDRINUSE :::59599  
```

The version **2.8.0** may still have a problem that we used to fix some time ago : ezPAARSE tried to start multiple times in some cases (when the PKBs had issues if I recall correctly).

A `docker-compose pull` may resolve this issue :)

**Comment by tporquet** [comment]
You're right: i was using an outdated ezpaarse instance
`docker-compose pull` did the trick, thanks!
