### ISSUE TITLE
Graylog geolocation question

### ISSUE THREAD

**Issue by jothoma1** [ezpaarse-project/ezpaarse#56]
Hi, 
thanks for this great tool, very useful!
We use Graylog https://www.graylog.org to visualize and ingest the date produced by ezpaarse. 
Is it possible to specify format and fields for geolocation ?
Graylog produce natively a map widget based on latitude,longitude but it must be formatted on an unique field containing "latitude" + "," + "longitude"
It is possible to do this ?
Thanks in advance !

Johan
Université de Rennes 1

**Comment by tporquet** [comment]
Hello Johan,

It is already feasible: you just need to specify that you want to add geoip-coordinates to the list of output fields. 
See:
![geoip-coordinates](https://cloud.githubusercontent.com/assets/2981650/22060221/3e2e6de0-dd70-11e6-91d9-704eb40c1bae.png)

It will give you a additional column containing data like:
[48.6333,2.45]

Hope it helps,
Thomas
