### ISSUE TITLE
slow git commit

### ISSUE THREAD

**Issue by kerphi** [ezpaarse-project/ezpaarse#61]
Because of the lint hook, each git commit is very slow (about 5 seconds on my machine)
I like to commit lot of atomic things but this slow step makes you want to commit only once a lot of things into the same commit.

Moreover, it checks also none ezpaarse code, for example platform one (which is not link checked on its side) so it's frustrating to be not allowed to abort its own commit cause someone else did not respect lint in the platforme code.

**Comment by nojhamster** [comment]
Fixed by 9c7eb316d390321dde8761f2f96c4d31900b84ae

**Comment by kerphi** [comment]
Thank you @nojhamster :+1:
