### ISSUE TITLE
Do not start if no mongo connection

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/ezpaarse#63]

**Comment by nojhamster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Empêcher le démarrage d'ezPAARSE si pas de mongoDB et générer une version d'ezPAARSE](https://trello.com/c/mY8Fmtsg/415-empecher-le-demarrage-d-ezpaarse-si-pas-de-mongodb-et-generer-une-version-d-ezpaarse)

**Comment by tporquet** [comment]
Super !!!
Bon week-end
Thomas

Le 2 juin 2017 17:17, "Yannick Schurter" <notifications@github.com> a
écrit :

**Comment by kerphi** [comment]
Merci Yannick
