### ISSUE TITLE
Can it use system node?

### ISSUE THREAD

**Issue by davisjam** [ezpaarse-project/ezpaarse#76]
This project downloads nvm (?) and uses node v8.6.0.

Is this a hard dependency, or can it run on more recent versions of node?
If it will work on more recent versions of node, how to configure this?

I see relevant-looking stuff in  `config.json` and `bin/buildnode` but would appreciate advice.

**Comment by nojhamster** [comment]
Hi ! As you noticed, ezPAARSE downloads `nvm` and the node version found in `config.json` on build, and it will use the global installation of node only if it matches the required version. You can change the node version by modifying `config.json` and run `make`, however it may not work as expected. As of now ezPAARSE won't start under node v10+ for a reason that is yet to be investigated.

**Comment by davisjam** [comment]
> As of now ezPAARSE won't start under node v10+ for a reason that is yet to be investigated.
Understood. Is there an issue open with a description of the failure? I don't see one?

FYI I'm asking because I'm pondering using ezPAARSE as a benchmark for the nodejs/benchmarking runs. In that context it would be useful if it worked on LTS or development versions of Node. See [this issue](https://github.com/nodejs/benchmarking/issues/6#issuecomment-426054677) and [this PR](https://github.com/nodejs/benchmarking/pull/243) if you'd like to chime in, correct any misunderstandings I have, etc.
