### ISSUE TITLE
Support for R5

### ISSUE THREAD

**Issue by benselme** [ezpaarse-project/ezpaarse#78]
Are there any plans for ezpaarse to support the new R5 spec ?

**Comment by tporquet** [comment]
Hello Béranger, can you be more specific? Is there a link to the R5 spec you mentionned?
Thanks

**Comment by benselme** [comment]
Sorry, I mean Counter Code of Practice Release 5, https://www.projectcounter.org/code-of-practice-five-sections/abstract/

Thank you

**Comment by tporquet** [comment]
Yes, we will most likely update our double-click procedure to follow the updated R5 algorithm https://www.projectcounter.org/code-of-practice-five-sections/7-processing-rules-underlying-counter-reporting-data/ 
For the reports and REST API, it remains to be discussed. 
A lot of what COUNTER R5 is about (counting unique items, etc.) can be done not directly by ezPAARSE but with our ezMESURE portal (based on Elastic and Kibana).
