### ISSUE TITLE
4003 : Line format was not recognized

### ISSUE THREAD

**Issue by waheed13085** [ezpaarse-project/ezpaarse#80]
Hi,
While processing the sample file available for download. I am getting the below error:

4003 : Line format was not recognized

Can you kindly assist. Thank you.

**Comment by tporquet** [comment]
Hello,

Which one of the sample files is causing the problem?
https://github.com/ezpaarse-project/ezpaarse-dataset-samples

On which instance of ezpaarse are you trying to process this log sample: a locally installed instance or our demo instance on demo.ezpaarse.org?

Best regards

**Comment by tporquet** [comment]
Incorrect install of docker compose, causing the error.
