### ISSUE TITLE
Manifest for 3.0.5 not found

### ISSUE THREAD

**Issue by zensense** [ezpaarse-project/ezpaarse#86]
When running `docker-compose up -d`, an error is thrown: `Error response from daemon: manifest for ezpaarseproject/ezpaarse:3.0.5 not found`.

A quick look at https://hub.docker.com/r/ezpaarseproject/ezpaarse/tags doesn't show a `3.0.5` tag. Build does run when one of the older tagged builds is supplied to [docker-compose.yml](https://github.com/ezpaarse-project/ezpaarse/blob/master/docker-compose.yml#L8)

**Comment by nojhamster** [comment]
Hi ! Indeed, the automated builds have been failing since the release of version `3.0.0`. We'll investigate this, expect a fix early next week. Thanks for reporting this !

**Comment by nojhamster** [comment]
There was an issue with some APT sources under debian Jessy. The dockerfile is now based on the latest node LTS (10.15.3) which uses debian Strech, and version `3.0.6` and above should now build without issue.
