### ISSUE TITLE
French Rtype fields.json descriptions in English

### ISSUE THREAD

**Issue by craigboman** [ezpaarse-project/ezpaarse#95]
Currently the rtypes from fields.json are pulled into the ezPaarse documentation. This is great and I support this mirroring, but I'm wondering if we can update the rtype descriptions in fields.json to support English descriptions. This would make it easier for English speaking users of ezPaarse. These are basic descriptions of the rtype fields, I may be able to get away with translating these programmatically and creating a pull request. Should I leave in the French rtype descriptions as well, or just convert it to English? I would like to find a way to describe rtypes in fields.json in both English and French if possible, unless it would make the fields.json file difficult to read.

**Comment by wilmouths** [comment]
Hello @craigboman,

A pull request [#253](https://github.com/ezpaarse-project/ezpaarse-platforms/pull/253) is awaiting validation. An other pull request [#125](https://github.com/ezpaarse-project/analogist/pull/125) on Analogist is also awaiting validation to support changes to the fields.json file.

**Comment by wilmouths** [comment]
Hello @craigboman 
Pull requests have been validated.
A new version of Analogist has been generated to display comments and descriptions of RTYPEs in English.
