### ISSUE TITLE
get lines which are not processed

### ISSUE THREAD

**Issue by shyamkhakhar9** [ezpaarse-project/ezpaarse#96]
@tporquet  I have log file which contains 1500 lines and when i inserted that file into ezpaarse it only processed 500. How can I know which lines didn't get processed?

**Comment by tporquet** [comment]
Hello @shyamkhakhar9 it is quite normal that ezpaarse rejects a lot of lines.
Those rejected lines are categorized and can be accessed if you ask ezpaarse to generate reject-files (see https://ezpaarse-project.github.io/ezpaarse/configuration/parametres.html#reject-files and https://ezpaarse-project.github.io/ezpaarse/essential/report.html#rejects).

This can be done from the command line (with the -H "Reject-Files: all" header)
or directly from the GUI:
![Capture du 2020-02-27 17-50-49](https://user-images.githubusercontent.com/2981650/75465976-b88f1d80-5989-11ea-8723-18fb17b3431c.png)
